# -*- coding: utf-8 -*-
"""coffee_leafs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2w6insMu96Wia5clY0I11TguLQ2gUKD
"""

from google.colab import drive 
drive.mount('/content/drive')

import cv2
import numpy as np
import matplotlib.pyplot as plt

from scipy import ndimage
from skimage.color import rgb2gray

plant = cv2.imread('/content/drive/MyDrive/data_plant/leaf_c.jpg')
plt.imshow(plant)
plt.show()

g = cv2.cvtColor(plant, cv2.COLOR_BGR2GRAY) 
plt.imshow(g)
plt.show()

blurry = cv2.GaussianBlur(g, (9, 9), 0)
plt.imshow(blurry)
plt.show()

clahe = cv2.createCLAHE(clipLimit = 2.0, tileGridSize=(8, 8)) 
claheNorm = clahe.apply(g) 
plt.imshow(claheNorm)
plt.show()

e1 = cv2.Canny(g, 100, 200) 

e2 = cv2.Canny(blurry, 100, 200) 

e3 = cv2.Canny(blurry, 100, 200)

labels = ['Original','Gray','Blurred','claheNorm','Edges','Canny Egde1','Cannny Edge2']
images = [plant,g,blurry,claheNorm,e1,e2,e3]
for i in range(len(labels)):
    plt.subplot(3,4,i+1),plt.imshow(images[i])
    plt.title(labels[i])
    plt.xticks([]),plt.yticks([])

plt.show()